include:
- ./func/*
kind: ArchiveUploadSpec
name: func-LDYl

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fn-get-term-a962fa2f-16ef-4f9d-8683-1efb5cf71a0c
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: env-get-term
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-LDYl
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-11T17:00:16Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fn-get-term
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: env-get-term
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_term
    packageref:
      name: fn-get-term-a962fa2f-16ef-4f9d-8683-1efb5cf71a0c
      namespace: default
  requestsPerPod: 10000
  resources: {}
